source "https://rubygems.org"
git_source(:github) {|repo| "https://github.com/#{repo}.git" }

ruby "3.3.7"

gem "mysql2", "~> 0.5"
gem "puma", ">= 5.0"
gem "rails", "~> 8.1.3"

gem "rack-cors"

gem "bootsnap", require: false

gem "config"

gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"
  gem "rspec-rails"
  gem "rubocop"
  gem "rubocop-faker"
  gem "rubocop-rails"
  gem "rubocop-rspec"
end
